<section class="contacts-page">
	<div class="container">
		<h3><i class="fa fa-map-marker"></i>OUR LOCATION</h3>
		<iframe width="100%" height="650" frameborder="0" style="border:0"
				src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ-UX3WdA2MEcRHHnJT8akBwU&key=AIzaSyCuOv8WkjpE5HOgK1niioSliejUzV5B6cg" allowfullscreen></iframe>
		<div class="contacts-as">
			<h4><i class="fa fa-paper-plane-o"></i>Message</h4>
			<h5>We will contact you within one business day.</h5>
			<form class="input-contacts">
				<div class="col-md-6 col-lg-6">
					<input type="text" name="text" placeholder="Name *" required>
					<input type="email" name="email" placeholder="Email *" required>
					<input type="tel" name="tel" placeholder="Phone">
				</div>
				<div class="col-md-6 col-lg-6">
					<textarea name="message" placeholder="Message *"></textarea>
					<button class="submit">SEND MESSAGE</button>
				</div>
			</form>
		</div>
	</div>
</section>