<section class="jumbotron text-center">
  <div class="container ">
    <h1>feel new level of services with us</h1>
      <section class="button">
          <a href="/public/index/services" class="btr btnn">
        <svg>
          <rect x="0" y="0" fill="none" width="100%" height="100%"/>
        </svg>
            Try now
        </a>
      </section>
  </div>
</section>
<section class="about text-center">
  <div class="container">
    <div class="down-h2">
      <h2>Why Us?</h2>
      <hr noshade>
      <p>Professional team with experience of work 5+ years</p>
  </div>
    <div class="col-md-3 col-lg-3">
      <div class="circle"><i class="fa fa-group"></i></div>
      <h3>best staff</h3>
      <hr noshade>
      <p>Our staff has experience in dealing with the problems of any complexity.</p>
    </div>
    <div class="col-md-3 col-lg-3">
      <div class="circle"><i class="fa fa-car"></i></div>
      <h3>original parts</h3>
      <hr noshade>
      <p>Repair of old parts and replacement of new ones</p>
    </div>
    <div class="col-md-3 col-lg-3">
      <div class="circle"><i class="fa fa-tachometer"></i></div>
      <h3>diagnostics</h3>
      <hr noshade>
      <p>We conduct inspection and computer diagnostics of your car</p>
    </div>
    <div class="col-md-3 col-lg-3">
      <div class="circle"><i class="fa fa-cogs"></i></div>
      <h3>settings</h3>
      <hr noshade>
      <p>Well as settings electronics and each detail of the car</p>
    </div>
  </div>
</section>
<section class="panel-auto">
  <div class="container">
<div class="col-md-6 col-lg-6">
  <div class="about-photo "></div>
</div>
<div class="col-md-6 col-lg-6 about-background">
  <h1>Brand car service</h1>
  <p>We offer the best service maintenance for the following brands vehicles</p>
  <section class="auto-service">
    <div class="row">
      <div class="col-md-4 col-lg-4 text-center">
      <p><i class="fa fa-check"></i>BMW</p>
        <p><i class="fa fa-check"></i>Renauult</p>
          <p><i class="fa fa-check"></i>Rover</p>
            <p><i class="fa fa-check"></i>Mitsubishi</p>
              <p><i class="fa fa-check"></i>Skoda</p>
    </div>
      <div class="col-md-4 col-lg-4 text-center">
      <p><i class="fa fa-check"></i>Audi</p>
        <p><i class="fa fa-check"></i>Lexus</p>
          <p><i class="fa fa-check"></i>Land Rover</p>
            <p><i class="fa fa-check"></i>Toyota</p>
              <p><i class="fa fa-check"></i>Ford</p>
    </div>
      <div class="col-md-4 col-lg-4 text-center">
        <p><i class="fa fa-check"></i>Nissan</p>
          <p><i class="fa fa-check"></i>Mercedes-Benz</p>
            <p><i class="fa fa-check"></i>Mazda</p>
              <p><i class="fa fa-check"></i>Kia</p>
                <p><i class="fa fa-check"></i>Volkswagen</p>
      </div>
      </div>
      </section>
  <button href="/public/index/services" class="btn"  > Discover More </button>
</div>
</div>
</section>
<section class="our-services">
  <div class="container text-center">
    <h2>Our Services</h2>
    <hr noshade>   <!--горизонтальна лінія-->
    <p>We perform diagnostics and repair of both US and domestic vehicles</p>
    <div class="col-md-4 col-lg-4">
      <div class="services-content">
      <div class="photo"></div>
      <div class="photo-label">Brake disc &amp; Pads</div>
    </div>
    </div>
    <div class="col-md-4 col-lg-4">
      <div class="services-content">
      <div class="photo2"></div>
      <div class="photo-label">Electrical Services</div>
    </div>
    </div>
    <div class="col-md-4 col-lg-4">
      <div class="services-content">
      <div class="photo3"></div>
      <div class="photo-label">Oil Change</div>
      </div>
</div>
</div>
</section>
<section class="quote">
  <div class="container text-center">
    <div class="quote-circle"><i class="fa fa-pencil"></i></div>
    <h2 class="quote-text">"Very happy with this service station, the staff is very good,
      professionals in their case, was replaced by oil and brake pads.
      I am quite satisfied with the work.I advise everyone who has a problem with the car,
      please contact these specialists"</h2>
      <hr noshade>
      <p>Peter Shved</p>
  </div>
</section>