<section class="make-order">
	<h1>Make order</h1>
	<hr>
	<h3>Turning to us. We, Help you with everything from oil changes to engine changes.
		We can handle any problem as the foreign and the domestic cars.</h3>
	<div class="container">
		<div class="about_auto">
			<h2>1</h2>
		</div>
			<h4>Information about car</h4>
		<form class="choice-auto">
			<select class="list-auto">
				<option value="Choose"selected>Choose...</option>
				<option value="BMW">BMW</option>
				<option value="Renauult">Renauult</option>
				<option value="Rover">Rover</option>
				<option value="Mitsubishi">Mitsubishi</option>
				<option value="Skoda">Skoda</option>
				<option value="Lexus" >Lexus</option>
				<option value="Land Rover">Land Rover</option>
				<option value="Toyota">Toyota</option>
				<option value="Ford">Ford</option>
				<option value="Nissan">Nissan</option>
				<option value="Mercedes-Benz">Mercedes-Benz</option>
				<option value="Mazda">Mazda</option>
				<option value="Kia">Kia</option>
				<option value="Volkswagen">Volkswagen</option>
				</select>
		</form>
		<div class="about_auto">
			<h2>2</h2>
		</div>
		<h4>Select services</h4>
		<form class="choice-services">
			<select class="list-services">
				<option value="Choose"selected>Choose...</option>
				<option value="1">Oil Change</option>
				<option value="2">Electrical Services</option>
				<option value="3">Brake Disc & Pads</option>
				<option value="4">Filter Replacement</option>
				<option value="5">Battery Replacement</option>
				<option value="6">Engine Diagnostics</option>
				<option value="7">Repair Transmissions</option>
				<option value="8">Repair Steering Rod</option>
				<option value="9">Replacement Shock Absorbers</option>
			</select>
		</form>
		<div class="about_auto">
			<h2>3</h2>
		</div>
		<h4>Contact details</h4>
		<div class="order">
			<form class="input-order">
				<div class="col-md-6 col-lg-6 input">
					<input type="text" name="text" placeholder="Name *" required>
					<input type="email" name="email" placeholder="Email *" required>
					<input type="tel" name="tel" placeholder="Phone">
				</div>
				<div class="col-md-6 col-lg-6 textarea">
					<textarea name="message" placeholder="Message *"></textarea>
					<button class="submit">SEND MESSAGE</button>
				</div>
			</form>
		</div>
	</div>
</section>